name: Publish NPM Package

on:
  push:
    branches:
      - main  # Change this to your default branch if it's different

jobs:
  npm-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Set Git User Identity
        run: |
          git config --global user.email "lanceu0128@gmail.com"
          git config --global user.name "lanceu0128"

      - name: Checkout
        uses: actions/checkout@v2

      - name: Update Version
        run: npm version patch

      - name: Install Dependencies
        run: npm install

      - name: Compile TypeScript
        run: npx tsc

      - name: Print NPM Token
        run: echo ${{ secrets.NPM_TOKEN }}

      - name: Publish to npm
        run: npm publish --access public  
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}  # Make sure you have an npm token as a secret
